-- Schema adapted for Oracle
-- Run as a privileged user (SYS) or a user with CREATE TABLE privileges

CREATE TABLE instituicoes (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(255) NOT NULL,
  cor VARCHAR2(50)
);

CREATE TABLE disciplinas (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  instituicao_id NUMBER NOT NULL,
  nome VARCHAR2(255) NOT NULL,
  codigo VARCHAR2(50),
  cor VARCHAR2(50),
  CONSTRAINT fk_disciplinas_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE CASCADE
);

CREATE TABLE turmas (
  id VARCHAR2(100) PRIMARY KEY,
  disciplina_id NUMBER NOT NULL,
  nome VARCHAR2(255) NOT NULL,
  CONSTRAINT fk_turmas_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) ON DELETE CASCADE
);

CREATE TABLE avaliacoes (
  id VARCHAR2(100) PRIMARY KEY,
  turma_id VARCHAR2(100) NOT NULL,
  nome VARCHAR2(255) NOT NULL,
  percentual NUMBER NOT NULL,
  CONSTRAINT fk_avaliacoes_turma FOREIGN KEY (turma_id) REFERENCES turmas(id) ON DELETE CASCADE
);

CREATE TABLE alunos (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  matricula VARCHAR2(100),
  nome VARCHAR2(255) NOT NULL,
  turma_id VARCHAR2(100),
  extras CLOB,
  CONSTRAINT fk_alunos_turma FOREIGN KEY (turma_id) REFERENCES turmas(id) ON DELETE SET NULL
);

CREATE TABLE notas (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  aluno_id NUMBER NOT NULL,
  avaliacao_id VARCHAR2(100) NOT NULL,
  valor NUMBER DEFAULT 0,
  CONSTRAINT fk_notas_aluno FOREIGN KEY (aluno_id) REFERENCES alunos(id) ON DELETE CASCADE,
  CONSTRAINT fk_notas_avaliacao FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes(id) ON DELETE CASCADE
);

CREATE TABLE logs (
  id VARCHAR2(200) PRIMARY KEY,
  timestamp VARCHAR2(100),
  "user" VARCHAR2(200),
  message CLOB
);

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  telefone VARCHAR2(50),
  senha_hash VARCHAR2(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ux_users_email ON users(email);
CREATE INDEX idx_disciplinas_instituicao ON disciplinas(instituicao_id);
CREATE INDEX idx_turmas_disciplina ON turmas(disciplina_id);
CREATE INDEX idx_alunos_turma ON alunos(turma_id);

CREATE TABLE password_resets (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  token VARCHAR2(200) NOT NULL UNIQUE,
  expires_at NUMBER NOT NULL
);

CREATE INDEX idx_password_resets_token ON password_resets(token);
